### ISSUE TITLE
Unable to Authenticate

### ISSUE THREAD

**Issue by ChipRab** [DrFaust92/terraform-provider-airflow#18]
It seems that there is some backend configuration required inside Composer/Airflow in order to make this work.  At a minimum, setting up master_authorized_networks, and possibly adding an authentication method to support this.  Doesn't matter what i do, I cannot make it work correctly.

I can't even make it work with Basic Authentication, so something needs to be configured with AirFlow to allow that.

**Comment by DrFaust92** [comment]
Hi [ChipRab](https://github.com/ChipRab), which distro of airflow are you using? this provider was tested with local airlfow (docker compose one that comes in airflow repo) and composer (managed google airflow) i was able to auth with basic config (composer requires extra steps)

**Comment by DrFaust92** [comment]
Closed for lack of response
