### ISSUE TITLE
Can't add multiple attributes to "extra" field when using airflow_connection ressource 

### ISSUE THREAD

**Issue by safazenoune** [DrFaust92/terraform-provider-airflow#29]
Hello, 

I am trying to use the `airflow_connection` ressource to create connections on my Composer Airflow, but i have errors when i try to add multiple attributes such as `key_secret_name` & `key_secret_project_id` on the `extra` field. It supports only string. Have you an example of usage please? 

My code : 
```
resource "airflow_connection" "test" {
  connection_id = "test"
  conn_type     = "google_cloud"
  extra = {
    "key_secret_name" = "test"
    "key_secret_project_id" = "test"
   }
}
``` 
The error i get :
```
│ Error: Incorrect attribute value type
│
│   on airflow_connection.tf line 5, in resource "airflow_connection" "test":
│    5:   extra = {
│    6:     "key_secret_name" = "test"
│    7:     "key_secret_project_id" = "test"
│    8:   }
│
│ Inappropriate value for attribute "extra": string required.
```
When i tried to create a connection juste with the type `google_cloud` it creates a connection with the `email` type.

**Comment by DrFaust92** [comment]
Hi @safazenoune have you tried sending it as a Jain string and not map? The provider follows the api and the api takes a string

**Comment by brokenjacobs** [comment]
Just wrap your map in jsonencode():
```
extra = jsonencode({
  "key_secret_name" = "test"
  "key_secret_project_id" = "test"
 })
```

**Comment by DrFaust92** [comment]
Closing for lack of response
