### ISSUE TITLE
[Feature] Add option to disable SSL certificate validation

### ISSUE THREAD

**Issue by allebacco** [DrFaust92/terraform-provider-airflow#31]
Hello, I am working with multiple Airflow instances deployed in a private cloud with self-signed SSL certificates.

I would like to disable SSL certificate validation the when configuring the provider. Should it be possible?

Thanks.

**Comment by DrFaust92** [comment]
checking

**Comment by DrFaust92** [comment]
Closing via  #32

@allebacco can you test latest version i cant really this this use case properly so this is a best effort PR

**Comment by allebacco** [comment]
Thanks for the PR, @DrFaust92 .

I will test it to report if it is working as expected.

Regards
